-- CREATE ROLE IF NOT EXISTS myuser WITH LOGIN PASSWORD 'mypassword';

-- CREATE DATABASE IF NOT EXISTS backend_db;

GRANT ALL PRIVILEGES ON DATABASE backend_db TO myuser;

CREATE SCHEMA IF NOT EXISTS backend;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA backend TO myuser;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS backend.leads (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    createdat TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedat TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    company VARCHAR(255),
    engaged BOOLEAN DEFAULT FALSE,
    stage INTEGER DEFAULT 0,
    lastContacted DATE NULL
);